name: CURL CLI ACTION
on: push
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: curl
      uses: enflo/curl-action@master
      with:
        curl: "https://web.mit.edu/hackl/www/lab/turkshop/slides/regex-cheatsheet.pdf"
